### ISSUE TITLE
UI Not Aligned, Irregular font sizes, Hero section not centralized

### ISSUE THREAD

**Issue by Stancobridge** [emmanuelejike/hulu-design#1]
You did a great job but the hero section is centralized in the center and buttons used is not the same with what they have in https://www.hulu.com/ webiste

Login Button => failed
TRY UP TO ONE MONTH FREE => Not literally visible to users
hulu => hero text is not as big as the one in hulu.com
HBO Max™, SHOWTIME®, CINEMAX® and STARZ® available as add-ons. => should not be bold
Free trial for new & eligible returning subscribers only => is small in size and faint in color

Use Capitalization where necessary

so many errors please check hulu.com and compare the design with your, make correction

redesign the header and hero section completely.
Thanks

**Comment by emmanuelejike** [comment]
> You did a great job but the hero section is centralized in the center and buttons used is not the same with what they have in https://www.hulu.com/ webiste
> 
> Login Button => failed
> TRY UP TO ONE MONTH FREE => Not literally visible to users
> hulu => hero text is not as big as the one in hulu.com
> HBO Max™, SHOWTIME®, CINEMAX® and STARZ® available as add-ons. => should not be bold
> Free trial for new & eligible returning subscribers only => is small in size and faint in color
> 
> Use Capitalization where necessary
> 
> so many errors please check hulu.com and compare the design with your, make correction
> 
> redesign the header and hero section completely.
> Thanks

Thanks for your corrections
Have worked on it
